name: Deploy Nuxt to Storybook
on: [workflow_dispatch]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # All history

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: install
        working-directory: ./services/front/dev
        run: yarn install --non-interactive

      - name: lint
        working-directory: ./services/front/dev
        run: yarn lint

      - name: test
        working-directory: ./services/front/dev
        run: yarn test

      - name: generate storybook
        working-directory: ./services/front/dev
        run: yarn storybook:build

      - name: Upload storybook site
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: services/front/dev/storybook-static

      - name: Deploy storybook to Firebase hosting
        working-directory: ./services/front
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |-
          npm install -g firebase-tools
          make deploy-prod-for-storybook
